from enum import Enum

## prover ##############################

class PastConfigs:
    def __init__(self, state: State, cycle: int) -> None: ...

    def next_deltas(
            self,
            state: State,
            cycle: int,
    ) -> tuple[int, int, int] | None: ...

    def delete_configs(self, state: State) -> None: ...

## parse ###############################

type Color = int
type State = int
type Shift = bool

type Slot = tuple[State, Color]
type Instr = tuple[Color, Shift, State]

type Params = tuple[State, Color]

type Prog = dict[Slot, Instr]

def tcompile(program: str) -> Prog: ...

def halt_slots(prog: str) -> list[Slot]: ...

def erase_slots(prog: str) -> list[Slot]: ...

def zero_reflexive_slots(prog: str) -> list[Slot]: ...

def show_state(state: State | None) -> str: ...

def show_slot(slot: Slot) -> str: ...

def show_instr(instr: Instr | None) -> str: ...

def read_instr(instr: str) -> Instr | None: ...

def show_comp(comp: Prog) -> str: ...

## machine #############################

class TermRes(Enum):
    undfnd = ...
    spnout = ...
    infrul = ...
    xlimit = ...

class MachineResult:
    result: TermRes

    steps: int
    cycles: int
    marks: int

    last_slot: Slot | None
    blanks: dict[State, int]

    def __init__(
            self,
            result: TermRes,
            steps: int,
            cycles: int,
            marks: int,
            last_slot: Slot | None,
            blanks: dict[State, int],
    ): ...

    @property
    def simple_termination(self) -> int | None: ...
    @property
    def undfnd(self) -> tuple[int, Slot] | None: ...
    @property
    def infrul(self) -> int | None: ...
    @property
    def spnout(self) -> int | None: ...
    @property
    def xlimit(self) -> int | None: ...

def run_quick_machine(prog: str, sim_lim: int) -> MachineResult: ...

def check_inf(prog: str, sim_lim: int) -> bool: ...
def term_or_rec(prog: str, sim_lim: int) -> bool: ...
def run_transcript(prog: str, sim_lim: int) -> bool: ...

## rules ###############################

Plus = int

type Mult = tuple[int, int]

type Op = Plus | Mult

type Index = tuple[int, int]

type Rule = dict[Index, Op]

## blocks ##############################

def opt_block(prog: str, steps: int) -> int: ...

## reason ##############################

class BackwardResult:
    @property
    def step(self) -> int: ...
    def is_refuted(self) -> bool: ...
    class refuted:
        ...
    class init:
        ...
    class step_limit:
        ...
    class depth_limit:
        ...

def bkw_cant_halt(prog: str, steps: int) -> BackwardResult: ...
def bkw_cant_blank(prog: str, steps: int) -> BackwardResult: ...
def bkw_cant_zloop(prog: str, steps: int) -> BackwardResult: ...
def bkw_cant_spinout(prog: str, steps: int) -> BackwardResult: ...
def bkw_cant_twostep(prog: str, steps: int) -> BackwardResult: ...

def cps_cant_halt(prog: str, rad: int) -> bool: ...
def cps_cant_blank(prog: str, rad: int) -> bool: ...
def cps_cant_spinout(prog: str, rad: int) -> bool: ...
def cps_cant_quasihalt(prog: str, rad: int) -> bool: ...

def far_cant_halt(prog: str, block_len: int) -> bool: ...
def far_cant_blank(prog: str, block_len: int) -> bool: ...
def far_cant_spinout(prog: str, block_len: int) -> bool: ...
