[package]
name = "tm"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
ahash = "*"
rayon = "*"
mimalloc = "*"
num-bigint = "*"
num-traits = "*"
num-integer = "*"
pyo3 = { version = "*", features = ["num-bigint"] }
