[package]
name = "export"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
tm = { path = "../tm" }
pyo3 = { version = "*", features = ["extension-module", "num-bigint"] }
