name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Ubuntu-Python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test C
        run: |
          cc --version
          make machines

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install pylint mypy coverage
          rustup update

      - name: Lint
        run: |
          make lint
          make clippy

      - name: Test Python
        run: |
          make coverage
          make test-all

      - name: Tree Gen
        run: |
          make generate

  Mac-Idris:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test C
        run: |
          cc --version
          make machines

      - name: Install Idris
        run: |
          brew --version
          brew update
          brew upgrade
          brew --version
          brew install coreutils
          brew install idris2

      - name: Test Idris
        run: make idris
